AWSTemplateFormatVersion: 2010-09-09
Description: This will create a lambda function and an api event which will trigger it. Also, lambda execution role

Transform: 'AWS::Serverless-2016-10-31'
Resources:
  fonefunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler
      Runtime: python3.7
      CodeUri: './src/fone.py'
      # CodeUri: 's3://my-code-bucket/my-function.zip'
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        foneapi:
            # Define an API Gateway endpoint that responds to HTTP GET at /thumbnail
            Type: Api
            Properties:
                Path: /hello
                Method: GET
      # Description: This is just a hello world lambda with api integration
      # MemorySize: 128
      # Timeout: 15
      # Policies:
      # - AWSLambdaExecute # Managed Policy
      # - Version: '2012-10-17' # Policy Document
      #   Statement:
      #     - Effect: Allow
      #       Action:
      #         - s3:GetObject
      #         - s3:GetObjectACL
      #       Resource: 'arn:aws:s3::lalitsam/*'
      # Environment:
      #   Variables:
      #     TABLE_NAME: my-table
      # Events:
      #   PhotoUpload:
      #     Type: S3
      #     Properties:
      #       Bucket: my-photo-bucket
      # Tags:
      #   Name: demo
        # DepartmentNameTag: ThumbnailDepartment
